import { storage } from "./storage";
import type { InsertCategory, InsertCollectible, InsertMedianPrice, InsertPriceHistory } from "@shared/schema";

// Categories with clean icons and descriptions
const categoriesData: InsertCategory[] = [
  { name: "Watches", slug: "watches", icon: "watch", description: "Luxury watches, vintage timepieces, and chronometers" },
  { name: "Trading Cards", slug: "trading-cards", icon: "cards", description: "Sports, Pokémon, MTG, and rare gaming cards" },
  { name: "Vinyl Records", slug: "vinyl-records", icon: "vinyl", description: "Vintage records, rare pressings, collectible albums" },
  { name: "Coins", slug: "coins", icon: "coin", description: "Rare coins, currency, and numismatics" },
  { name: "Sports Collectibles", slug: "sports-collectibles", icon: "sports", description: "Memorabilia, autographs, game-used items" },
  { name: "Collector Cars", slug: "collector-cars", icon: "car", description: "Classic/vintage automobiles and collectibles" },
  { name: "Military", slug: "military", icon: "military", description: "Military memorabilia and historical artifacts" },
  { name: "Art", slug: "art", icon: "art", description: "Fine art, sculptures, and contemporary pieces" },
];

// Seed collectibles reference category by slug; IDs are generated by DB
type SeedCollectible = Omit<InsertCollectible, "categoryId"> & { categorySlug?: string };

const collectiblesSeed: SeedCollectible[] = [
  // Luxury Watches
  {
    name: "Rolex Submariner Date",
    description: "Iconic diving watch with date display and unidirectional bezel. Reference 126610LN in stainless steel with black dial and ceramic bezel.",
    categorySlug: "watches",
    brand: "Rolex",
    model: "Submariner Date 126610LN",
    year: 2020,
    condition: "Excellent",
    imageUrl: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1000&q=80",
    tags: ["luxury", "diving", "steel", "automatic"],
    metadata: { caseDiameter: "41mm", movement: "Caliber 3235", waterResistance: "300m", bracelet: "Oyster" },
  },
  {
    name: "Patek Philippe Nautilus",
    description: "Legendary sports luxury watch. Reference 5711/1A-010 in stainless steel with blue horizontal embossed dial.",
    categorySlug: "watches",
    brand: "Patek Philippe",
    model: "Nautilus 5711/1A-010",
    year: 2019,
    condition: "New",
    imageUrl: "https://images.unsplash.com/photo-1594576662830-a558fae5b143?auto=format&fit=crop&w=1000&q=80",
    tags: ["luxury", "discontinued", "steel", "automatic"],
    metadata: { caseDiameter: "40mm", movement: "Caliber 324 S C", waterResistance: "120m", bracelet: "Integrated" },
  },
  {
    name: "Audemars Piguet Royal Oak",
    description: "Iconic octagonal luxury sports watch. Reference 15202ST in stainless steel with blue dial.",
    categorySlug: "watches",
    brand: "Audemars Piguet",
    model: "Royal Oak 15202ST",
    year: 2021,
    condition: "Excellent",
    imageUrl: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1000&q=80",
    tags: ["luxury", "octagonal", "steel", "thin"],
    metadata: { caseDiameter: "39mm", movement: "Caliber 2121", thickness: "8.1mm", bracelet: "Integrated" },
  },

  // Trading Cards - Sports
  {
    name: "2003 LeBron James Rookie Card",
    description: "Upper Deck Exquisite Collection RPA #78/99. BGS 9.5 Gem Mint with 10 Autograph.",
    categorySlug: "trading-cards",
    brand: "Upper Deck",
    model: "Exquisite Collection",
    year: 2003,
    condition: "BGS 9.5",
    imageUrl: "https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?auto=format&fit=crop&w=1000&q=80",
    tags: ["rookie", "autographed", "patch", "graded"],
    metadata: { player: "LeBron James", cardNumber: "78/99", grader: "BGS", grade: "9.5" },
  },
  {
    name: "1952 Mickey Mantle Topps #311",
    description: "The holy grail of baseball cards. PSA 8 NM-MT condition.",
    categorySlug: "trading-cards",
    brand: "Topps",
    model: "1952 Baseball",
    year: 1952,
    condition: "PSA 8",
    imageUrl: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=1000&q=80",
    tags: ["vintage", "baseball", "hall-of-fame", "graded"],
    metadata: { player: "Mickey Mantle", cardNumber: "311", grader: "PSA", grade: "8" },
  },

  // Trading Cards - Pokemon
  {
    name: "1998 Pikachu Illustrator",
    description: "Rarest Pokémon card; contest prize. PSA 10 Gem Mint.",
    categorySlug: "trading-cards",
    brand: "Pokémon",
    model: "Promo",
    year: 1998,
    condition: "PSA 10",
    imageUrl: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=1000&q=80",
    tags: ["pokemon", "promo", "japanese", "graded"],
    metadata: { pokemon: "Pikachu", rarity: "Promo", language: "Japanese", population: "Very Low" },
  },

  // Vinyl Records
  {
    name: "The Beatles - Abbey Road",
    description: "Original UK pressing from 1969. Apple Records PCS 7088.",
    categorySlug: "vinyl-records",
    brand: "Apple Records",
    model: "PCS 7088",
    year: 1969,
    condition: "Near Mint",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1000&q=80",
    tags: ["beatles", "original-pressing", "uk", "stereo"],
    metadata: { artist: "The Beatles", label: "Apple Records", pressing: "UK Original", matrix: "YEX 749-2" },
  },
  {
    name: "Led Zeppelin IV",
    description: "Original UK pressing Atlantic 2401012. Some labels misprint 'Led Zepplin'.",
    categorySlug: "vinyl-records",
    brand: "Atlantic",
    model: "2401012",
    year: 1971,
    condition: "VG+",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1000&q=80",
    tags: ["led-zeppelin", "original-pressing", "uk", "classic-rock"],
    metadata: { artist: "Led Zeppelin", label: "Atlantic", pressing: "UK Original", notes: "Misprint label variant" },
  },

  // Coins
  {
    name: "1933 Double Eagle",
    description: "Most valuable gold coin. One of few legal examples. PCGS MS65.",
    categorySlug: "coins",
    brand: "US Mint",
    model: "Saint-Gaudens Double Eagle",
    year: 1933,
    condition: "PCGS MS65",
    imageUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1000&q=80",
    tags: ["gold", "rare", "american", "graded"],
    metadata: { denomination: "$20", composition: "Gold", weight: "33.431g", mintage: "445,500" },
  },

  // Collector Cars
  {
    name: "1955 Mercedes-Benz 300SL Gullwing",
    description: "Iconic gullwing doors and racing heritage. Restored, matching numbers.",
    categorySlug: "collector-cars",
    brand: "Mercedes-Benz",
    model: "300SL Gullwing",
    year: 1955,
    condition: "Concours Restored",
    imageUrl: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1000&q=80",
    tags: ["gullwing", "classic", "racing-heritage", "restored"],
    metadata: { engine: "3.0L Inline-6", transmission: "4-Speed Manual", mileage: "45,000", color: "Silver Metallic" },
  },
];

function randomBetween(min: number, max: number) {
  return Math.random() * (max - min) + min;
}

function generateMedianPrices(collectibleIds: string[]): InsertMedianPrice[] {
  const results: InsertMedianPrice[] = [];
  const today = new Date();
  for (const id of collectibleIds) {
    // deterministic base by hash of id
    let hash = 0;
    for (let i = 0; i < id.length; i++) hash = (hash * 31 + id.charCodeAt(i)) >>> 0;
    const base = 500 + (hash % 200000); // 500 .. ~200,500
    let current = base;
    for (let d = 30; d >= 0; d--) {
      const date = new Date(today);
      date.setDate(today.getDate() - d);
      const volatility = 0.02 + (hash % 10) / 1000; // small tweak per id
      const delta = (Math.random() - 0.5) * volatility;
      const prev = current;
      current = Math.max(1, current * (1 + delta));
      const dayChange = ((current - prev) / (prev || 1)) * 100;
      results.push({
        collectibleId: id,
        date,
        medianPrice: current.toFixed(2),
        dayChange: dayChange.toFixed(2),
        activeListings: Math.floor(randomBetween(5, 30)),
        granularity: "day",
      });
    }
  }
  return results;
}

function generateRecentPriceHistory(collectibleIds: string[]): InsertPriceHistory[] {
  const sources = ["eBay", "Heritage Auctions"];
  const out: InsertPriceHistory[] = [];
  for (const id of collectibleIds) {
    const entries = Math.floor(randomBetween(2, 5));
    for (let i = 0; i < entries; i++) {
      out.push({
        collectibleId: id,
        source: sources[i % sources.length],
        price: randomBetween(100, 50000).toFixed(2),
        condition: Math.random() > 0.5 ? "Excellent" : undefined,
      });
    }
  }
  return out;
}

export async function seedDatabase() {
  try {
    console.log("Starting database seeding...");

    // Seed categories (id auto-generated)
    for (const category of categoriesData) {
      try {
        await storage.createCategory(category);
        console.log(`Created category: ${category.name}`);
      } catch {
        // ignore duplicates
      }
    }

    // Build categoryId map by slug
    const categories = await storage.getCategories();
    const categoryBySlug = new Map(categories.map(c => [c.slug, c.id]));

    // Seed collectibles with resolved categoryId
    const insertedIds: string[] = [];
    for (const seed of collectiblesSeed) {
      const insert: InsertCollectible = {
        name: seed.name,
        description: seed.description,
        categoryId: seed.categorySlug ? categoryBySlug.get(seed.categorySlug) : undefined,
        brand: seed.brand,
        model: seed.model,
        year: seed.year,
        condition: seed.condition,
        imageUrl: seed.imageUrl,
        tags: seed.tags,
        metadata: seed.metadata,
      };
      try {
        const created = await storage.createCollectible(insert);
        insertedIds.push(created.id);
        console.log(`Created collectible: ${created.name}`);
      } catch {
        // Try to find existing by name
        const found = (await storage.searchCollectibles(seed.name)).find(c => c.name === seed.name);
        if (found) {
          insertedIds.push(found.id);
          console.log(`Using existing collectible: ${found.name}`);
        }
      }
    }

    // Generate and insert median prices (bulk in chunks)
    console.log("Generating median prices...");
    const medianData = generateMedianPrices(insertedIds);
    const chunkSize = 500;
    for (let i = 0; i < medianData.length; i += chunkSize) {
      const chunk = medianData.slice(i, i + chunkSize);
      await storage.bulkInsertMedianPrices(chunk);
    }
    console.log(`Inserted median prices: ${medianData.length}`);

    // Add a small set of recent price history entries (scrapedAt defaults to now)
    console.log("Seeding recent price history...");
    const history = generateRecentPriceHistory(insertedIds);
    for (const h of history) {
      try {
        await storage.addPriceData(h);
      } catch {
        // ignore duplicates
      }
    }
    console.log(`Inserted price history records: ${history.length}`);

    console.log("Database seeding completed successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}
